import type { CrewLang } from '@/lib/crew/types'

// Every word a crew member reads, in English and in Spanish. The Spanish is
// the jobsite's, not a textbook's, and follows the crew card in SOP-006
// (Appendix C) where that card already says it.

const EN = {
  loading: 'Loading…',
  noConnection: 'No connection. Check your signal.',
  tryAgain: 'Try again',
  cancel: 'Cancel',
  send: 'Send',
  save: 'Save',
  close: 'Close',
  yes: 'Yes',
  no: 'No',
  optional: 'optional',

  tabToday: 'Today',
  tabWeek: 'Week',
  tabHours: 'Hours',
  tabMore: 'More',

  morning: 'Good morning',
  afternoon: 'Good afternoon',
  evening: 'Good evening',

  // the clock
  onClock: 'On the clock',
  offClock: 'Off the clock',
  since: (time: string) => `since ${time}`,
  todayTotal: (hours: string) => `${hours} today`,
  clockIn: 'Clock in',
  clockOut: 'Clock out',
  changeJob: 'Change job',
  whichJob: 'Which job?',
  otherJob: 'Another job, not on the list',
  otherJobName: 'Job name or address',
  noJobs: 'The office has not added any jobs yet. Use "Another job" and type where you are.',
  lunch: 'Lunch break (not paid)',
  lunchNone: 'None',
  note: 'Note',
  locationNote: 'Your location is saved once, when you tap. Never while you work.',
  clockedIn: (job: string, time: string) => `Clocked in at ${job}, ${time}.`,
  clockedOut: (hours: string) => `Clocked out. ${hours} today.`,
  changedJob: (job: string) => `Now on ${job}.`,
  punchWaiting: 'Saved on this phone. It sends as soon as you have signal.',
  punchWaitingIn: (job: string, time: string) => `Clock in · ${job} · ${time}`,
  punchWaitingOut: (time: string) => `Clock out · ${time}`,
  punchWaitingSwitch: (job: string, time: string) => `Change to ${job} · ${time}`,
  sendNow: 'Send now',
  officeWillCheck: 'The office will look at this one',

  // schedule
  yourJobToday: "Today's job",
  yourJobTomorrow: 'Tomorrow',
  startAt: (time: string) => `Start ${time}`,
  directions: 'Directions',
  gotIt: 'Got it',
  cantMakeIt: 'I cannot make it',
  cantWhy: 'What happened?',
  youSaidOk: 'You said you will be there',
  youSaidCant: 'You said you cannot make it',
  nothingToday: 'Nothing scheduled for you today.',
  nothingScheduled: 'Nothing scheduled yet. The office sends it the night before.',
  schedule: 'Your schedule',
  tellOffice: 'Tell the office',

  // questions
  officeAsks: 'The office needs to know',
  answer: 'Your answer',
  sendAnswer: 'Send answer',
  stillWorking: 'I am still working',
  iLeftAt: 'I left at',
  openForm: 'Fill it in',
  amountLabel: 'Amount',

  // quick actions
  send_: 'Send to the office',
  receipt: 'Receipt',
  receiptHint: 'Paper receipt from the store',
  progress: 'Progress',
  progressHint: 'Photos and what got done',
  eod: 'End of day',
  eodHint: 'Close out the day',
  noteToOffice: 'Note',
  noteHint: 'Tell the office something',

  // receipt
  receiptTitle: 'Paper receipt',
  receiptPhoto: 'Take a photo of the whole receipt, flat, with the total showing.',
  addPhoto: 'Add photo',
  takePhoto: 'Take photo',
  amount: 'Total (if you can read it)',
  store: 'Store',
  whoPaid: 'Who paid?',
  paidCompany: 'Company card or account',
  paidMe: 'My own money',
  paidMeNote: 'The office will see that you are owed this.',
  whatFor: 'What was it for?',
  job: 'Job',
  receiptSent: 'Receipt sent.',
  needPhoto: 'Add a photo of the receipt.',

  // progress
  progressTitle: 'Progress',
  progressWhat: 'What got done? What does the photo show?',
  progressTip: 'Photos of every wall before it is covered.',
  progressSent: 'Sent.',
  needNoteOrPhoto: 'Add a photo or a note.',

  // end of day
  eodTitle: 'End of day',
  eodDone: 'What got done today?',
  eodStuck: 'Anything stuck or in the way?',
  eodNeeds: 'What do you need for tomorrow?',
  eodNeedsHint: 'Material, tools, people.',
  eodMore: 'More to report',
  eodAsked: 'Did anyone ask for work that is not on the plans?',
  eodAskedHint: 'Tell them: "I will write it up today and Marco will price it. We keep going on the contract work."',
  eodAskedWhat: 'Who asked, and for what?',
  eodDeliveries: 'Did material arrive?',
  eodDeliveriesWhat: 'What came? Did the count match?',
  eodVisits: 'Inspections or visitors?',
  eodVisitsWhat: 'Who came, and what did they say?',
  eodSafety: 'Anyone hurt, or a close call?',
  eodSafetyWhat: 'What happened?',
  eodDecision: 'Anything Marco has to decide?',
  eodDecisionWhat: 'What does he need to decide?',
  eodPhotos: 'Photos',
  eodSend: 'Close the day',
  eodSent: 'Day closed. Thank you.',
  eodNeedDone: 'Say what got done today.',
  eodFiled: 'End of day sent',
  eodForYesterday: 'This is for yesterday',

  // note
  noteTitle: 'Note to the office',
  noteWhat: 'What should the office know?',
  noteSent: 'The office has it.',
  noJob: 'No job',

  // tasks
  tasks: 'Your tasks',
  noTasks: 'No tasks right now.',
  done: 'Done',
  markDone: 'Mark done',
  blocked: 'I am stuck',
  blockedWhy: 'What is in the way?',
  doneNote: 'Anything to add?',
  due: (day: string) => `Due ${day}`,
  taskDone: 'Marked done.',
  taskBlocked: 'The office knows you are stuck.',
  reopen: 'Not done yet',
  stuck: 'Stuck',

  // sent list
  sentToday: 'Sent today',
  sentRecently: 'Sent this week',
  nothingSent: 'Nothing sent yet today.',
  stNew: 'Sent',
  stFiled: 'Filed',
  stNeeds: 'Needs a look',
  stApproved: 'Approved',
  stDenied: 'Not approved',
  stWaiting: 'Waiting on the office',
  kindReceipt: 'Receipt',
  kindProgress: 'Progress',
  kindEod: 'End of day',
  kindNote: 'Note',
  kindTimefix: 'Time fix',
  photos: (n: number) => (n === 1 ? '1 photo' : `${n} photos`),

  // hours
  hoursTitle: 'Your hours',
  thisWeek: 'This week',
  lastWeek: 'Last week',
  total: 'Total',
  noHours: 'No hours this week yet.',
  stillOn: 'still on the clock',
  breakOf: (min: number) => `${min} min break`,
  fixTitle: 'Fix my time',
  fixIntro: 'Forgot to clock in or out? Tell the office the real times. They decide, and you get a notice.',
  fixDay: 'Day',
  fixIn: 'In',
  fixOut: 'Out',
  fixWhy: 'What happened?',
  fixSend: 'Send to the office',
  fixSent: 'Sent. The office will decide.',
  fixRequests: 'Your requests',
  wrong: 'Something wrong with your hours?',
  hoursNote: 'Hours shown here are what the office sees. Pay is figured by the office.',

  // more
  language: 'Language',
  install: 'Put it on your phone',
  installed: 'Installed. You are using the app from your home screen.',
  installIos: 'On iPhone: open this page in Safari, tap Share, then "Add to Home Screen".',
  installAndroid: 'On Android: open the menu (three dots), then "Install app" or "Add to Home screen".',
  installThen: 'The first time you open it from the home screen it asks for your email and a code once more.',
  installNow: 'Install',
  notifications: 'Notifications',
  notifyOn: 'On for this phone',
  notifyOff: 'Off',
  notifyWhat: 'Tomorrow\'s job, a new task, a question from the office.',
  turnOn: 'Turn on',
  turnOff: 'Turn off',
  notifyBlocked: 'Notifications are blocked for this app in your phone settings.',
  notifyIosFirst: 'On iPhone, put the app on your home screen first. Then you can turn notifications on.',
  notifyUnsupported: 'This browser cannot show notifications.',
  signedInAs: 'Signed in as',
  signOut: 'Sign out',
  photoFailed: 'That photo did not upload. Try again.',
  uploading: 'Uploading…',
  remove: 'Remove',
}

type Strings = typeof EN

const ES: Strings = {
  loading: 'Cargando…',
  noConnection: 'Sin conexión. Revisa tu señal.',
  tryAgain: 'Intentar de nuevo',
  cancel: 'Cancelar',
  send: 'Mandar',
  save: 'Guardar',
  close: 'Cerrar',
  yes: 'Sí',
  no: 'No',
  optional: 'opcional',

  tabToday: 'Hoy',
  tabWeek: 'Semana',
  tabHours: 'Horas',
  tabMore: 'Más',

  morning: 'Buenos días',
  afternoon: 'Buenas tardes',
  evening: 'Buenas noches',

  onClock: 'En turno',
  offClock: 'Fuera de turno',
  since: (time) => `desde las ${time}`,
  todayTotal: (hours) => `${hours} hoy`,
  clockIn: 'Marcar entrada',
  clockOut: 'Marcar salida',
  changeJob: 'Cambiar de trabajo',
  whichJob: '¿Qué trabajo?',
  otherJob: 'Otro trabajo, no está en la lista',
  otherJobName: 'Nombre o dirección del trabajo',
  noJobs: 'La oficina todavía no agrega trabajos. Usa "Otro trabajo" y escribe dónde estás.',
  lunch: 'Descanso de comida (sin pago)',
  lunchNone: 'Ninguno',
  note: 'Nota',
  locationNote: 'Tu ubicación se guarda una sola vez, al tocar. Nunca mientras trabajas.',
  clockedIn: (job, time) => `Entrada marcada en ${job}, ${time}.`,
  clockedOut: (hours) => `Salida marcada. ${hours} hoy.`,
  changedJob: (job) => `Ahora en ${job}.`,
  punchWaiting: 'Guardado en este teléfono. Se manda en cuanto tengas señal.',
  punchWaitingIn: (job, time) => `Entrada · ${job} · ${time}`,
  punchWaitingOut: (time) => `Salida · ${time}`,
  punchWaitingSwitch: (job, time) => `Cambio a ${job} · ${time}`,
  sendNow: 'Mandar ahora',
  officeWillCheck: 'La oficina va a revisar este',

  yourJobToday: 'Trabajo de hoy',
  yourJobTomorrow: 'Mañana',
  startAt: (time) => `Entrada ${time}`,
  directions: 'Cómo llegar',
  gotIt: 'Enterado',
  cantMakeIt: 'No puedo ir',
  cantWhy: '¿Qué pasó?',
  youSaidOk: 'Dijiste que ahí estarás',
  youSaidCant: 'Dijiste que no puedes ir',
  nothingToday: 'No tienes nada programado hoy.',
  nothingScheduled: 'Todavía no hay nada programado. La oficina lo manda la noche anterior.',
  schedule: 'Tu horario',
  tellOffice: 'Avisar a la oficina',

  officeAsks: 'La oficina necesita saber',
  answer: 'Tu respuesta',
  sendAnswer: 'Mandar respuesta',
  stillWorking: 'Sigo trabajando',
  iLeftAt: 'Salí a las',
  openForm: 'Llenarlo',
  amountLabel: 'Cantidad',

  send_: 'Mandar a la oficina',
  receipt: 'Recibo',
  receiptHint: 'Recibo en papel de la tienda',
  progress: 'Avance',
  progressHint: 'Fotos y lo que se hizo',
  eod: 'Fin del día',
  eodHint: 'Cerrar el día',
  noteToOffice: 'Nota',
  noteHint: 'Avisar algo a la oficina',

  receiptTitle: 'Recibo en papel',
  receiptPhoto: 'Toma una foto del recibo completo, plano, donde se vea el total.',
  addPhoto: 'Agregar foto',
  takePhoto: 'Tomar foto',
  amount: 'Total (si se alcanza a leer)',
  store: 'Tienda',
  whoPaid: '¿Quién pagó?',
  paidCompany: 'Tarjeta o cuenta de la compañía',
  paidMe: 'Mi propio dinero',
  paidMeNote: 'La oficina verá que se te debe.',
  whatFor: '¿Para qué fue?',
  job: 'Trabajo',
  receiptSent: 'Recibo enviado.',
  needPhoto: 'Agrega una foto del recibo.',

  progressTitle: 'Avance',
  progressWhat: '¿Qué se hizo? ¿Qué muestra la foto?',
  progressTip: 'Fotos de cada pared antes de taparla.',
  progressSent: 'Enviado.',
  needNoteOrPhoto: 'Agrega una foto o una nota.',

  eodTitle: 'Fin del día',
  eodDone: '¿Qué se hizo hoy?',
  eodStuck: '¿Algo atorado o que estorbe?',
  eodNeeds: '¿Qué necesitas para mañana?',
  eodNeedsHint: 'Material, herramienta, gente.',
  eodMore: 'Más que reportar',
  eodAsked: '¿Alguien pidió algo que no está en los planos?',
  eodAskedHint: 'Diles: "Lo anoto hoy y Marco lo cotiza. Seguimos con lo del contrato mientras."',
  eodAskedWhat: '¿Quién lo pidió y qué pidió?',
  eodDeliveries: '¿Llegó material?',
  eodDeliveriesWhat: '¿Qué llegó? ¿Coincidió la cuenta?',
  eodVisits: '¿Inspecciones o visitas?',
  eodVisitsWhat: '¿Quién vino y qué dijo?',
  eodSafety: '¿Alguien lastimado o algún susto?',
  eodSafetyWhat: '¿Qué pasó?',
  eodDecision: '¿Algo que Marco tenga que decidir?',
  eodDecisionWhat: '¿Qué tiene que decidir?',
  eodPhotos: 'Fotos',
  eodSend: 'Cerrar el día',
  eodSent: 'Día cerrado. Gracias.',
  eodNeedDone: 'Escribe qué se hizo hoy.',
  eodFiled: 'Fin del día enviado',
  eodForYesterday: 'Esto es de ayer',

  noteTitle: 'Nota a la oficina',
  noteWhat: '¿Qué debe saber la oficina?',
  noteSent: 'La oficina ya la tiene.',
  noJob: 'Sin trabajo',

  tasks: 'Tus tareas',
  noTasks: 'No tienes tareas por ahora.',
  done: 'Hecho',
  markDone: 'Marcar como hecho',
  blocked: 'Estoy atorado',
  blockedWhy: '¿Qué te detiene?',
  doneNote: '¿Algo que agregar?',
  due: (day) => `Para ${day}`,
  taskDone: 'Marcado como hecho.',
  taskBlocked: 'La oficina ya sabe que estás atorado.',
  reopen: 'Todavía no está',
  stuck: 'Atorado',

  sentToday: 'Enviado hoy',
  sentRecently: 'Enviado esta semana',
  nothingSent: 'Todavía no mandas nada hoy.',
  stNew: 'Enviado',
  stFiled: 'Registrado',
  stNeeds: 'Hay que revisarlo',
  stApproved: 'Aprobada',
  stDenied: 'No aprobada',
  stWaiting: 'Esperando a la oficina',
  kindReceipt: 'Recibo',
  kindProgress: 'Avance',
  kindEod: 'Fin del día',
  kindNote: 'Nota',
  kindTimefix: 'Corrección de horas',
  photos: (n) => (n === 1 ? '1 foto' : `${n} fotos`),

  hoursTitle: 'Tus horas',
  thisWeek: 'Esta semana',
  lastWeek: 'Semana pasada',
  total: 'Total',
  noHours: 'Todavía no hay horas esta semana.',
  stillOn: 'sigues en turno',
  breakOf: (min) => `${min} min de descanso`,
  fixTitle: 'Corregir mis horas',
  fixIntro: '¿Se te olvidó marcar entrada o salida? Dile a la oficina las horas reales. Ellos deciden y te llega un aviso.',
  fixDay: 'Día',
  fixIn: 'Entrada',
  fixOut: 'Salida',
  fixWhy: '¿Qué pasó?',
  fixSend: 'Mandar a la oficina',
  fixSent: 'Enviado. La oficina decide.',
  fixRequests: 'Tus solicitudes',
  wrong: '¿Algo está mal en tus horas?',
  hoursNote: 'Estas horas son las que ve la oficina. El pago lo calcula la oficina.',

  language: 'Idioma',
  install: 'Ponla en tu teléfono',
  installed: 'Instalada. Estás usando la app desde tu pantalla de inicio.',
  installIos: 'En iPhone: abre esta página en Safari, toca Compartir y luego "Agregar a inicio".',
  installAndroid: 'En Android: abre el menú (tres puntos) y luego "Instalar app" o "Agregar a pantalla principal".',
  installThen: 'La primera vez que la abras desde la pantalla de inicio te pide tu correo y un código una vez más.',
  installNow: 'Instalar',
  notifications: 'Avisos',
  notifyOn: 'Activados en este teléfono',
  notifyOff: 'Desactivados',
  notifyWhat: 'El trabajo de mañana, una tarea nueva, una pregunta de la oficina.',
  turnOn: 'Activar',
  turnOff: 'Desactivar',
  notifyBlocked: 'Los avisos están bloqueados para esta app en los ajustes de tu teléfono.',
  notifyIosFirst: 'En iPhone, primero pon la app en tu pantalla de inicio. Después puedes activar los avisos.',
  notifyUnsupported: 'Este navegador no puede mostrar avisos.',
  signedInAs: 'Sesión de',
  signOut: 'Cerrar sesión',
  photoFailed: 'Esa foto no se subió. Intenta de nuevo.',
  uploading: 'Subiendo…',
  remove: 'Quitar',
}

export const STRINGS: Record<CrewLang, Strings> = { en: EN, es: ES }
export type CrewStrings = Strings
