-- Seed the Ops board with the 40 cards from the operating model of 2026-09-04.
-- Idempotent: existing ids are left alone so moves made on the board survive re-runs.
insert into public.ops_cards (id, title, owner, col, note, sort, updated_by) values
  ('sop-001', 'SOP-001 Purchasing and receipts', 'Lando', 'measured', 'Job name at the register, receipts same day, $500 rule. Grade line 37/40.', 10, 'seed-2026-09-04'),
  ('sop-002', 'SOP-002 Change orders', 'Marco', 'measured', 'Every addition of $1,000+ is its own CO before work starts. Weekly invoice-growth query.', 20, 'seed-2026-09-04'),
  ('sop-003', 'SOP-003 Job creation and naming', 'Lando', 'measured', 'Job exists before the first dollar. USPS street address.', 30, 'seed-2026-09-04'),
  ('sop-004', 'SOP-004 Sub payment', 'Ilene', 'live', 'Cadence per sub, promise kept. Past-due detector runs weekly.', 40, 'seed-2026-09-04'),
  ('sop-005', 'SOP-005 Estimate intake and transmission', 'Marco', 'review', 'Lead source mandatory, revision queue, follow-ups. 80% of the estimating-admin job.', 50, 'seed-2026-09-04'),
  ('sop-006', 'SOP-006 Project execution (PM lifecycle)', 'Lando', 'drafting', 'Six gates, daily log, directive capture, disputes ladder, closeout retro.', 60, 'seed-2026-09-04'),
  ('sop-007', 'SOP-007 Contract and billing terms', 'Lando', 'drafting', 'Terms standard, GC redline list, invoice package rule, AR ladder, lien hygiene.', 70, 'seed-2026-09-04'),
  ('eli-charter', 'Eli PM charter, signed by both', 'Marco', 'review', 'Drafted July 22. Marco edits, both sign, it becomes an Operating Document.', 80, 'seed-2026-09-04'),
  ('handoff-bellevue', 'Bellevue AC938 handoff packet', 'Lando', 'drafting', 'Pre-filled from the record. Brackets close when the subcontract arrives.', 90, 'seed-2026-09-04'),
  ('bellevue-redline', 'Bellevue subcontract read before DocuSign', 'Lando', 'backlog', 'SOP-007 §3 checklist, one email to Marco, then he signs.', 100, 'seed-2026-09-04'),
  ('daily-log', 'Daily log template plus 5 pm nag', 'Lando', 'backlog', 'Email to info@ with subject LOG <address> <date>; KB ingests; bot nags.', 110, 'seed-2026-09-04'),
  ('co-intake', 'CO / directive intake template plus ledger row', 'Lando', 'backlog', 'Confirming email → ledger row "awaiting price" with age alert.', 120, 'seed-2026-09-04'),
  ('quality-checklists', 'Framing, insulation, drywall checklists', 'Eli', 'drafting', 'SOP-006 Appendix B. Eli marks up from the field, then it prints.', 130, 'seed-2026-09-04'),
  ('billing-calendar', 'Per-job billing cutoffs in tasks.py', 'Ilene', 'backlog', 'AFT closes the 23rd. Schifferer from the subcontract.', 140, 'seed-2026-09-04'),
  ('invoice-package', 'Invoice package rule', 'Ilene', 'backlog', 'Waiver attached, named contact, receipt confirmed in one day, ledger row open.', 150, 'seed-2026-09-04'),
  ('ar-ladder', 'AR ladder drafts, day +1 to +30', 'Ilene', 'backlog', 'Bot drafts, human sends. Marco from day +14.', 160, 'seed-2026-09-04'),
  ('residential-contract', 'Saddlewood Agreement template to counsel', 'Marco', 'backlog', 'SOP-007 §1 with Marco''s numbers filled, one flat-fee review.', 170, 'seed-2026-09-04'),
  ('gc-redline', 'GC subcontract redline checklist', 'Lando', 'drafting', 'SOP-007 §2, ten items in priority order.', 180, 'seed-2026-09-04'),
  ('decision-log', 'EOD check-in parsed into a decision log', 'Lando', 'backlog', 'ASK: what | why Marco | rule? y/n. Weekly count per job.', 190, 'seed-2026-09-04'),
  ('scorecard-query', 'Job scorecard SQL plus weekly-report section', 'Lando', 'backlog', 'Hours, receipts, invoices, COs, commitments per job.', 200, 'seed-2026-09-04'),
  ('safety-program', 'Safety manual activation', 'Eli', 'backlog', 'Appendix E signatures, toolbox talks logged, SDS binder in the truck.', 210, 'seed-2026-09-04'),
  ('training-es', 'Spanish crew guides for SOP-002 to SOP-006', 'Eli', 'backlog', 'TRAINING-SOP-001 is the format: read aloud, then the visor card.', 220, 'seed-2026-09-04'),
  ('hire-estimating-admin', 'Estimating and Sales Admin hire', 'Marco', 'live', 'Postings live since August. Owns SOP-005 on day one.', 230, 'seed-2026-09-04'),
  ('hire-bookkeeper', 'Bookkeeper / AP-AR hire', 'Marco', 'backlog', 'Or Ilene plus the ladder and the invoice package rule.', 240, 'seed-2026-09-04'),
  ('ops-review', 'Friday 30-minute Ops Board review', 'Lando', 'backlog', 'Lando plus Marco. Which escalations become rules; which cards move.', 250, 'seed-2026-09-04'),
  ('buildero-receipts', 'Buildero receipt upload with job picker', 'Lando', 'backlog', 'Kills the register-PO problem at the UI. First adoption step.', 260, 'seed-2026-09-04'),
  ('buildero-co', 'Buildero change orders as first-class documents', 'Lando', 'backlog', 'SOP-002 enforced by the product; invoice blocks undocumented lines.', 270, 'seed-2026-09-04'),
  ('buildero-lifecycle', 'Buildero: SOP-006 gates, daily log, PM scorecard', 'Lando', 'backlog', 'The lifecycle as project phases with gates.', 280, 'seed-2026-09-04'),
  ('lien-hygiene', '20-day preliminary notice routine', 'Ilene', 'backlog', 'Every job, routine paperwork. Counsel confirms the prime rule.', 290, 'seed-2026-09-04'),
  ('ghl-hygiene', 'GHL: source and dollar value mandatory', 'Marco', 'backlog', 'Two zero-scoring grade lines. Config plus habit, not code.', 300, 'seed-2026-09-04'),
  ('sop-008', 'SOP-008 Subs and vendors: contract family plus bid-out pipeline', 'Lando', 'drafting', 'Seven documents, seven stages, honest-comparison rule, award thresholds.', 310, 'seed-2026-09-04'),
  ('sub-msa', 'Master Subcontract Agreement template to counsel', 'Marco', 'backlog', 'Once per sub, annual. Same flat-fee review as the client agreement.', 320, 'seed-2026-09-04'),
  ('work-order', 'Work order template from the leveled bid', 'Lando', 'backlog', 'Two pages, variables only. References the MSA.', 330, 'seed-2026-09-04'),
  ('po-terms', 'Purchase order terms on every order of $500 or more', 'Ilene', 'backlog', 'Storage and cancellation fees stated up front. The Facings tile lesson.', 340, 'seed-2026-09-04'),
  ('flow-down', 'Flow-down exhibit from the GC subcontract extraction', 'Lando', 'backlog', 'Pay-when-paid timing, retainage, waivers, safety, schedule. Bellevue first.', 350, 'seed-2026-09-04'),
  ('sub-onboarding', 'Sub onboarding packet', 'Ilene', 'backlog', 'MSA, COI, W-9, ROC check, safety, cadence, ACH confirmed by phone.', 360, 'seed-2026-09-04'),
  ('bid-out-pipeline', 'Bid-out pipeline: package, invite, parse, level, award, contract', 'Lando', 'backlog', 'Bot parses quotes into the leveling sheet; PM recommends; Marco awards above $10k.', 370, 'seed-2026-09-04'),
  ('sub-scorecard', 'Sub scorecard at closeout', 'Eli', 'backlog', 'Dates, rework, callbacks, invoicing hygiene, would-rehire. Feeds the next leveling sheet.', 380, 'seed-2026-09-04'),
  ('buildero-platform-map', 'Buildero platform map: exists, specced, build next', 'Lando', 'drafting', 'Object by object from the schema and the August 5 audits. Ten-item build order.', 390, 'seed-2026-09-04'),
  ('bonus-plan-v2', 'PM bonus v2: tranches, callback window, boosts, gates', 'Marco', 'review', 'Marco sets X and the flat boost amounts. Paid on cash, held 90 days.', 400, 'seed-2026-09-04')
on conflict (id) do nothing;
